---
- name: Provisionar Projeto Korp
  hosts: local
  connection: local
  become: true

  vars:
    project_path: /mnt/c/Users/lucas/projeto-korp-devops

  roles:
    - docker

  tasks:

    - name: Verificar se rede existe
      command: docker network inspect korp-network
      register: network_check
      failed_when: false
      changed_when: false

    - name: Criar rede Docker
      command: docker network create korp-network
      when: network_check.rc != 0

    - name: Subir containers
      command: docker compose up --build -d
      args:
        chdir: "{{ project_path }}"

    - name: Aguardar aplicação iniciar
      pause:
        seconds: 10

    - name: Validar endpoint
      uri:
        url: http://localhost/projeto-korp
        return_content: true
      register: api_response

    - name: Exibir resposta da API
      debug:
        msg: "{{ api_response.content }}"